# Generated by Django 5.1 on 2024-08-07 19:18

import django.core.validators
import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_apartment_apartmentimage_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='occupant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='occupant',
            name='house_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='occupant',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='occupant',
            name='mobile_phone',
            field=models.CharField(max_length=15, null=True, verbose_name=django.db.models.fields.IntegerField),
        ),
        migrations.AddField(
            model_name='occupant',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('completed', 'Sale Completed')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupants', to='myapp.apartment'),
        ),
    ]
