# Generated by Django 5.1 on 2024-08-08 01:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_apartment_listing_type_apartment_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='number_of_rooms',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='status',
        ),
        migrations.AddField(
            model_name='apartment',
            name='amenities_available',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='images1',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='number_of_buildings',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='types_of_houses_available',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images2', models.JSONField()),
                ('building_name', models.CharField(max_length=255)),
                ('number_of_floors', models.PositiveIntegerField()),
                ('total_units', models.PositiveIntegerField()),
                ('units_available', models.PositiveIntegerField()),
                ('units_occupied', models.PositiveIntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='myapp.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='myapp.building')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images3', models.JSONField()),
                ('house_number', models.CharField(max_length=50)),
                ('house_type', models.CharField(choices=[('bed_sitter', 'Bed Sitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('four_bedroom', 'Four Bedroom'), ('five_bedroom', 'Five Bedroom')], default='one_bedroom', max_length=50)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('both', 'Both')], max_length=10)),
                ('house_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=50)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='myapp.building')),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='myapp.floor')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='myapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[('bed_sitter', 'Bed Sitter'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom'), ('four_bedroom', 'Four Bedroom'), ('five_bedroom', 'Five Bedroom')], default='one_bedroom', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('id_number', models.IntegerField(null=True, unique=True)),
                ('mobile_phone', models.CharField(max_length=15, null=True)),
                ('move_in_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('completed', 'Sale Completed')], default='unpaid', max_length=10)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('rent_deficit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_days_paid', models.IntegerField(default=0)),
                ('garbage_payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('completed', 'Sale Completed')], default='unpaid', max_length=10)),
                ('last_garbage_payment_date', models.DateField(blank=True, null=True)),
                ('garbage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='myapp.building')),
                ('floor_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='myapp.floor')),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='myapp.house')),
            ],
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='myapp.house')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='myapp.tenant')),
            ],
        ),
        migrations.DeleteModel(
            name='Occupant',
        ),
    ]
